# Generated by Django 3.1.7 on 2021-03-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='emprego.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagem_empresa',
            field=models.ImageField(blank=True, upload_to='emprego/media'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='salario_oferecido',
            field=models.TextField(),
        ),
    ]
